### ISSUE TITLE
Data usage of SSE stream

### ISSUE THREAD

**Issue by danielfaust** [bitswired/rustgpt#1]
An issue I noticed was that the SSE were sending the *entire* text for each update. Is this a limitation imposed by HTMX? In that case some Javascript code receiving them directly and aggregating them into a response and updating the page would be a better approach.

**Comment by danielfaust** [comment]
Great project, though!

**Comment by jimzer** [comment]
Thanks for the feedback 👍🏽

You're right, in the current version I parse the AI generated text as markdown in the server.
So for each new chunk of text, I parse the markdown and send the HTML to display. 

I agree it's not optimal, it was mainly to make a simple working solution. 

It would be more network-efficient to just stream the text and parse the markdown on the client 👍🏽
